services:
  seo-data-api-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: se-ranking/seo-data-api-mcp-server
    container_name: se-ranking-seo-data-api-mcp-server
    restart: unless-stopped
    environment:
      - DATA_API_TOKEN=${DATA_API_TOKEN:-}
      - PROJECT_API_TOKEN=${PROJECT_API_TOKEN:-}
    stdin_open: true
    tty: true
